export const CLASSROOM_CREATED = 'CLASSROOM_CREATED'
export const CLASSROOM_UPDATED = 'CLASSROOM_UPDATED'
export const CLASSROOM_REMOVED = 'CLASSROOM_REMOVED'
export const CLASSROOM_STUDENTS_UPDATED = 'CLASSROOM_STUDENTS_UPDATED'
